set shiftwidth=2
set tabstop=2
set expandtab
set autoindent
set background=dark
syntax on

au BufRead,BufNewFile *.pp set filetype=ruby

let &t_SI .= "\<Esc>[?2004h"
let &t_EI .= "\<Esc>[?2004l"

inoremap <special> <expr> <Esc>[200~ XTermPasteBegin()

function! XTermPasteBegin()
  set pastetoggle=<Esc>[201~
  set paste
  return ""
endfunction
