set shiftwidth=2
set tabstop=2
set expandtab
set autoindent
set background=dark
syntax on
set nu rnu

" automatically set pp files to ruby filetype syntax highlighting
au BufRead,BufNewFile *.pp set filetype=ruby

" automatically set py files to use pydoc
autocmd BufNewFile,BufRead *.py set keywordprg=pydoc3

" begin: automatically toggle paste mode so no need to use :set paste
let &t_SI .= "\<Esc>[?2004h"
let &t_EI .= "\<Esc>[?2004l"

inoremap <special> <expr> <Esc>[200~ XTermPasteBegin()

function! XTermPasteBegin()
  set pastetoggle=<Esc>[201~
  set paste
  return ""
endfunction
" end: automatic toggle paste mode

" stop vim from putting comments automatically for new lines
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=0
" set comment color to green
hi Comment ctermfg=green
